        <!-- footer -->
        <footer id="footer">
            <div class="footer-wrap inner-layer">
                <div class="footer-logo"><img src="/assets/image/common/footer-logo.png" alt=""></div>
                <ul>
                    <li>
                        <p>(04510) 서울특별시 중구 청파로 464, 101동 3104호 (중림동, 브라운스톤서울)</p>
                    </li>
                    <li>
                        <p><span>TEL </span><a href="tel:02-3676-1333">(02) 3676-1333</a></p>
                        <p><span>FAX </span>(02) 3676-1339</p>
                        <p><span>EMAIL </span><a href="mailto:office@emergency.or.kr">office@emergency.or.kr</a></p>
                    </li>
                    <li>
                        <p><span>COPYRIGHT 대한응급의학회 (THE KOREAN SOCIETY OF EMERGENCY MEDICINE) ALL RIGHTS RESERVED.</span></p>
                    </li>
                </ul>
            </div>
        </footer>
        <!-- //footer -->
    </div>
</body>
</html>