<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>2025년도 대한응급의학회 춘계학술대회</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=0,maximum-scale=10,user-scalable=yes,viewport-fit=cover">
    <meta name="format-detection" content="telephone=no, address=no, email=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta http-equiv="Expires" content="0">
    <meta http-equiv="Pragma" content="no-cache">

    <meta name="Author" content="2025년도 대한응급의학회 춘계학술대회">
    <meta name="Keywords" content="2025년도 대한응급의학회 춘계학술대회">
    <meta name="description" content="2025년도 대한응급의학회 춘계학술대회">
    <meta property="og:title" content="2025년도 대한응급의학회 춘계학술대회">
    <link rel="icon" href="/assets/image/favicon.ico">

    <link rel="stylesheet" href="/assets/css/jquery-ui.min.css">
    <link rel="stylesheet" href="/assets/css/slick.css">
    <link rel="stylesheet" href="/assets/css/common.css">

    <script src="/assets/js/jquery-1.12.4.min.js"></script>
    <script src="/assets/js/jquery-ui.min.js"></script>
    <script src="/assets/js/slick.min.js"></script>
    <script src="/assets/js/common.js"></script>
</head>
<body>
    
    <!-- 
        main일 때 class="main"
        sub일 때 class="sub"
    -->
    <div id="wrap" class="sub">
        <!-- header -->
        <header id="header" class="js-header">
            <div class="header-wrap inner-layer">
                <h1 class="header-logo"><a href="#n"><img src="/assets/image/common/h1-logo.png" alt=""></a></h1>
                <div class="right">
                    <div class="top t-hide">
                        <div class="dday-wrap">
                            <img src="/assets/image/common/ic_dday.png" alt="">
                            <p class="today">TODAY 2023.01.01</p>
                            <p class="dday">D - 000</p>
                        </div>
                        <div class="util-menu-wrap m-hide">
                            <ul class="util-menu">
                                <li><a href="#n">대한응급의학회 홈페이지</a></li>
                                <li><a href="#n">행사 HOME</a></li>
                                <li><a href="#n">지난 학술대회 바로가기</a></li>
                                <li><a href="#n">ADMIN</a></li>
                            </ul>
                        </div>
                    </div>
                    <nav id="gnb">
                        <div class="m-gnb-header t-show m-show">
                            <a href="#n" class="btn btn-link">대한응급의학회 홈페이지</a>
                            <div class="util-wrap">
                                <ul class="util-menu">
                                    <li><a href="#n">SIGN UP</a></li>
                                    <li><a href="#n">LOGIN</a></li>
                                    <li><a href="#n">ADMIN</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="gnb-wrap">
                            <ul class="gnb js-gnb">
                                <li>
                                    <a href="#n"><span>인사말</span></a>
                                    <ul>
                                        <li><a href="#n">인사말</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#n"><span>학회 프로그램</span></a>
                                    <ul>
                                        <li><a href="#n">전체 프로그램</a></li>
                                        <li><a href="#n">세부 프로그램</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#n"><span>초록 구연 및 포스터접수</span></a>
                                    <ul>
                                        <li><a href="#n">초록접수 안내</a></li>
                                        <li><a href="#n">초록접수</a></li>
                                        <li><a href="#n">초록접수 수정 및 확인</a></li>
                                        <li><a href="#n">초록심사</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#n"><span>사전등록</span></a>
                                    <ul>
                                        <li><a href="#n">사전등록 안내</a></li>
                                        <li><a href="#n">사전등록</a></li>
                                        <li><a href="#n">사전등록 확인 및 영수증</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#n"><span>강의원고</span></a>
                                    <ul>
                                        <li><a href="#n">강의원고 접수 안내</a></li>
                                        <li><a href="#n">강의원고 접수</a></li>
                                        <li><a href="#n">강의원고 수정 및 확인</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#n"><span>워크숍 신청</span></a>
                                    <ul>
                                        <li><a href="#n">워크숍 등록 안내</a></li>
                                        <li><a href="#n">워크숍 신청</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#n"><span>행사장 안내</span></a>
                                    <ul>
                                        <li><a href="#n">오시는 길</a></li>
                                        <li><a href="#n">부스 배치도</a></li>
                                        <li><a href="#n">학회장 보기</a></li>
                                        <li><a href="#n">호텔 예약 안내</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <button type="button" class="btn btn-menu-close js-btn-menu-close"><span class="hide">메뉴 닫기</span></button>
                    </nav>
                </div>
                <a href="#n" class="btn-home t-show m-show"><img src="/assets/image/common/ic_home.png" alt="Home"></a>
                <button type="button" class="btn btn-menu-open js-btn-menu-open"><span class="hide">메뉴 열기</span></button>
            </div>
            <div id="dim" class="js-dim"></div>
        </header>
        <!-- //header -->